name: run_pydsd_ci.yml
on: [push]
jobs:
  build_and_publish:
    name: Setup Environment, and run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pydsdci
          environment-file: pydsd-ci.yml
      - name: Run Pytest
        run: |
          conda list #Do we stay in activate environment between steps? 
          pytest