name: run_pydsd_ci.yml
on: [push]
jobs:
  build_and_publish:
    name: Setup Environment, and run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pydsdci
          environment-file: pydsd-ci.yml
      - name: Run Pytest
        shell: bash -l {0}
        run: |
          pytest
      - name: Publish package to PYPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        shell: bash -l {0}
        run: |
	  python setup.py sdist bdist_wheel
	  env
	  twine upload --repository testpypi dist/*
